## <font color=[TPL_STATUS_COLOR]>[TPL_REPO_FULL_NAME] build [TPL_BUILD_STATUS] (`takes [TPL_BUILD_CONSUMING]s`) </font>

`Event`: [TPL_BUILD_EVENT] ~ [TPL_COMMIT_TAG]

`Stage`: [TPL_STAGE_NAME]

`Message`: [TPL_COMMIT_MSG]

`Detail`: [[TPL_COMMIT_SHA]]([TPL_COMMIT_LINK])

`Author`: [[TPL_AUTHOR_NAME]([TPL_AUTHOR_EMAIL])](mailto:[TPL_AUTHOR_EMAIL])

[Click To The Build Detail Page [TPL_STATUS_EMOTICON]]([TPL_BUILD_LINK])
